//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientePuntodeVentas.PuntoVentasSW {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleVenta_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DetalleVenta_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_detalleField;
        
        private int Id_ventaField;
        
        private int Id_productoField;
        
        private int CantidadField;
        
        private double SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_detalle {
            get {
                return this.Id_detalleField;
            }
            set {
                if ((this.Id_detalleField.Equals(value) != true)) {
                    this.Id_detalleField = value;
                    this.RaisePropertyChanged("Id_detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_venta {
            get {
                return this.Id_ventaField;
            }
            set {
                if ((this.Id_ventaField.Equals(value) != true)) {
                    this.Id_ventaField = value;
                    this.RaisePropertyChanged("Id_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Id_producto {
            get {
                return this.Id_productoField;
            }
            set {
                if ((this.Id_productoField.Equals(value) != true)) {
                    this.Id_productoField = value;
                    this.RaisePropertyChanged("Id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleados_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Empleados_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_empleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string puestoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_empleado {
            get {
                return this.id_empleadoField;
            }
            set {
                if ((this.id_empleadoField.Equals(value) != true)) {
                    this.id_empleadoField = value;
                    this.RaisePropertyChanged("id_empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string puesto {
            get {
                return this.puestoField;
            }
            set {
                if ((object.ReferenceEquals(this.puestoField, value) != true)) {
                    this.puestoField = value;
                    this.RaisePropertyChanged("puesto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Clientes_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Clientes_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_cliente {
            get {
                return this.Id_clienteField;
            }
            set {
                if ((this.Id_clienteField.Equals(value) != true)) {
                    this.Id_clienteField = value;
                    this.RaisePropertyChanged("Id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ventas_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Ventas_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_ventaField;
        
        private int Id_clienteField;
        
        private int Id_empleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_ventaField;
        
        private double TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_venta {
            get {
                return this.Id_ventaField;
            }
            set {
                if ((this.Id_ventaField.Equals(value) != true)) {
                    this.Id_ventaField = value;
                    this.RaisePropertyChanged("Id_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Id_cliente {
            get {
                return this.Id_clienteField;
            }
            set {
                if ((this.Id_clienteField.Equals(value) != true)) {
                    this.Id_clienteField = value;
                    this.RaisePropertyChanged("Id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Id_empleado {
            get {
                return this.Id_empleadoField;
            }
            set {
                if ((this.Id_empleadoField.Equals(value) != true)) {
                    this.Id_empleadoField = value;
                    this.RaisePropertyChanged("Id_empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Fecha_venta {
            get {
                return this.Fecha_ventaField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_ventaField, value) != true)) {
                    this.Fecha_ventaField = value;
                    this.RaisePropertyChanged("Fecha_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Productos_VO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Productos_VO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private double PrecioField;
        
        private int StockField;
        
        private int Id_proveedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_producto {
            get {
                return this.Id_productoField;
            }
            set {
                if ((this.Id_productoField.Equals(value) != true)) {
                    this.Id_productoField = value;
                    this.RaisePropertyChanged("Id_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Id_proveedor {
            get {
                return this.Id_proveedorField;
            }
            set {
                if ((this.Id_proveedorField.Equals(value) != true)) {
                    this.Id_proveedorField = value;
                    this.RaisePropertyChanged("Id_proveedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PuntoVentasSW.WebServicePuntodeVentasSoap")]
    public interface WebServicePuntodeVentasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Detalle", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Productos_VO))]
        ClientePuntodeVentas.PuntoVentasSW.Get_DetalleResponse Get_Detalle(ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Detalle", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_DetalleResponse> Get_DetalleAsync(ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Empleados", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Productos_VO))]
        ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosResponse Get_Empleados(ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Empleados", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosResponse> Get_EmpleadosAsync(ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Clientes", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Productos_VO))]
        ClientePuntodeVentas.PuntoVentasSW.Get_ClientesResponse Get_Clientes(ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Clientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_ClientesResponse> Get_ClientesAsync(ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametros del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Ventas", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ClientePuntodeVentas.PuntoVentasSW.Productos_VO))]
        ClientePuntodeVentas.PuntoVentasSW.Get_VentasResponse Get_Ventas(ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Ventas", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_VentasResponse> Get_VentasAsync(ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Eliminar_EmpleadosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Empleados", ReplyAction="*")]
        ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosResponse Eliminar_Empleados(ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar_Empleados", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosResponse> Eliminar_EmpleadosAsync(ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_Producto", ReplyAction="*")]
        ClientePuntodeVentas.PuntoVentasSW.insert_ProductoResponse insert_Producto(ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert_Producto", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.insert_ProductoResponse> insert_ProductoAsync(ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_DetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Detalle", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequestBody Body;
        
        public Get_DetalleRequest() {
        }
        
        public Get_DetalleRequest(ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_DetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros;
        
        public Get_DetalleRequestBody() {
        }
        
        public Get_DetalleRequestBody(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_DetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_DetalleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Get_DetalleResponseBody Body;
        
        public Get_DetalleResponse() {
        }
        
        public Get_DetalleResponse(ClientePuntodeVentas.PuntoVentasSW.Get_DetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_DetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO[] Get_DetalleResult;
        
        public Get_DetalleResponseBody() {
        }
        
        public Get_DetalleResponseBody(ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO[] Get_DetalleResult) {
            this.Get_DetalleResult = Get_DetalleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_EmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Empleados", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequestBody Body;
        
        public Get_EmpleadosRequest() {
        }
        
        public Get_EmpleadosRequest(ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_EmpleadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros;
        
        public Get_EmpleadosRequestBody() {
        }
        
        public Get_EmpleadosRequestBody(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_EmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_EmpleadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosResponseBody Body;
        
        public Get_EmpleadosResponse() {
        }
        
        public Get_EmpleadosResponse(ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_EmpleadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Empleados_VO[] Get_EmpleadosResult;
        
        public Get_EmpleadosResponseBody() {
        }
        
        public Get_EmpleadosResponseBody(ClientePuntodeVentas.PuntoVentasSW.Empleados_VO[] Get_EmpleadosResult) {
            this.Get_EmpleadosResult = Get_EmpleadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_ClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Clientes", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequestBody Body;
        
        public Get_ClientesRequest() {
        }
        
        public Get_ClientesRequest(ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_ClientesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros;
        
        public Get_ClientesRequestBody() {
        }
        
        public Get_ClientesRequestBody(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_ClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_ClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Get_ClientesResponseBody Body;
        
        public Get_ClientesResponse() {
        }
        
        public Get_ClientesResponse(ClientePuntodeVentas.PuntoVentasSW.Get_ClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_ClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Clientes_VO[] Get_ClientesResult;
        
        public Get_ClientesResponseBody() {
        }
        
        public Get_ClientesResponseBody(ClientePuntodeVentas.PuntoVentasSW.Clientes_VO[] Get_ClientesResult) {
            this.Get_ClientesResult = Get_ClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_VentasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Ventas", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequestBody Body;
        
        public Get_VentasRequest() {
        }
        
        public Get_VentasRequest(ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_VentasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros;
        
        public Get_VentasRequestBody() {
        }
        
        public Get_VentasRequestBody(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            this.parametros = parametros;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_VentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_VentasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Get_VentasResponseBody Body;
        
        public Get_VentasResponse() {
        }
        
        public Get_VentasResponse(ClientePuntodeVentas.PuntoVentasSW.Get_VentasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_VentasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Ventas_VO[] Get_VentasResult;
        
        public Get_VentasResponseBody() {
        }
        
        public Get_VentasResponseBody(ClientePuntodeVentas.PuntoVentasSW.Ventas_VO[] Get_VentasResult) {
            this.Get_VentasResult = Get_VentasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Eliminar_EmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar_Empleados", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequestBody Body;
        
        public Eliminar_EmpleadosRequest() {
        }
        
        public Eliminar_EmpleadosRequest(ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Eliminar_EmpleadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public Eliminar_EmpleadosRequestBody() {
        }
        
        public Eliminar_EmpleadosRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Eliminar_EmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Eliminar_EmpleadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosResponseBody Body;
        
        public Eliminar_EmpleadosResponse() {
        }
        
        public Eliminar_EmpleadosResponse(ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Eliminar_EmpleadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Eliminar_EmpleadosResult;
        
        public Eliminar_EmpleadosResponseBody() {
        }
        
        public Eliminar_EmpleadosResponseBody(string Eliminar_EmpleadosResult) {
            this.Eliminar_EmpleadosResult = Eliminar_EmpleadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_ProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_Producto", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequestBody Body;
        
        public insert_ProductoRequest() {
        }
        
        public insert_ProductoRequest(ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_ProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.Productos_VO producto;
        
        public insert_ProductoRequestBody() {
        }
        
        public insert_ProductoRequestBody(ClientePuntodeVentas.PuntoVentasSW.Productos_VO producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insert_ProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insert_ProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientePuntodeVentas.PuntoVentasSW.insert_ProductoResponseBody Body;
        
        public insert_ProductoResponse() {
        }
        
        public insert_ProductoResponse(ClientePuntodeVentas.PuntoVentasSW.insert_ProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insert_ProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insert_ProductoResult;
        
        public insert_ProductoResponseBody() {
        }
        
        public insert_ProductoResponseBody(string insert_ProductoResult) {
            this.insert_ProductoResult = insert_ProductoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePuntodeVentasSoapChannel : ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePuntodeVentasSoapClient : System.ServiceModel.ClientBase<ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap>, ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap {
        
        public WebServicePuntodeVentasSoapClient() {
        }
        
        public WebServicePuntodeVentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePuntodeVentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePuntodeVentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePuntodeVentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePuntodeVentas.PuntoVentasSW.Get_DetalleResponse ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Get_Detalle(ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequest request) {
            return base.Channel.Get_Detalle(request);
        }
        
        public ClientePuntodeVentas.PuntoVentasSW.DetalleVenta_VO[] Get_Detalle(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequestBody();
            inValue.Body.parametros = parametros;
            ClientePuntodeVentas.PuntoVentasSW.Get_DetalleResponse retVal = ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Get_Detalle(inValue);
            return retVal.Body.Get_DetalleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_DetalleResponse> ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Get_DetalleAsync(ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequest request) {
            return base.Channel.Get_DetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_DetalleResponse> Get_DetalleAsync(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Get_DetalleRequestBody();
            inValue.Body.parametros = parametros;
            return ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Get_DetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosResponse ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Get_Empleados(ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequest request) {
            return base.Channel.Get_Empleados(request);
        }
        
        public ClientePuntodeVentas.PuntoVentasSW.Empleados_VO[] Get_Empleados(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequestBody();
            inValue.Body.parametros = parametros;
            ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosResponse retVal = ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Get_Empleados(inValue);
            return retVal.Body.Get_EmpleadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosResponse> ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Get_EmpleadosAsync(ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequest request) {
            return base.Channel.Get_EmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosResponse> Get_EmpleadosAsync(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Get_EmpleadosRequestBody();
            inValue.Body.parametros = parametros;
            return ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Get_EmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePuntodeVentas.PuntoVentasSW.Get_ClientesResponse ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Get_Clientes(ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequest request) {
            return base.Channel.Get_Clientes(request);
        }
        
        public ClientePuntodeVentas.PuntoVentasSW.Clientes_VO[] Get_Clientes(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequestBody();
            inValue.Body.parametros = parametros;
            ClientePuntodeVentas.PuntoVentasSW.Get_ClientesResponse retVal = ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Get_Clientes(inValue);
            return retVal.Body.Get_ClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_ClientesResponse> ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Get_ClientesAsync(ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequest request) {
            return base.Channel.Get_ClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_ClientesResponse> Get_ClientesAsync(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Get_ClientesRequestBody();
            inValue.Body.parametros = parametros;
            return ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Get_ClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePuntodeVentas.PuntoVentasSW.Get_VentasResponse ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Get_Ventas(ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequest request) {
            return base.Channel.Get_Ventas(request);
        }
        
        public ClientePuntodeVentas.PuntoVentasSW.Ventas_VO[] Get_Ventas(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequestBody();
            inValue.Body.parametros = parametros;
            ClientePuntodeVentas.PuntoVentasSW.Get_VentasResponse retVal = ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Get_Ventas(inValue);
            return retVal.Body.Get_VentasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_VentasResponse> ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Get_VentasAsync(ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequest request) {
            return base.Channel.Get_VentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Get_VentasResponse> Get_VentasAsync(ClientePuntodeVentas.PuntoVentasSW.ArrayOfAnyType parametros) {
            ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Get_VentasRequestBody();
            inValue.Body.parametros = parametros;
            return ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Get_VentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosResponse ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Eliminar_Empleados(ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequest request) {
            return base.Channel.Eliminar_Empleados(request);
        }
        
        public string Eliminar_Empleados(int id) {
            ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequestBody();
            inValue.Body.id = id;
            ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosResponse retVal = ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Eliminar_Empleados(inValue);
            return retVal.Body.Eliminar_EmpleadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosResponse> ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.Eliminar_EmpleadosAsync(ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequest request) {
            return base.Channel.Eliminar_EmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosResponse> Eliminar_EmpleadosAsync(int id) {
            ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.Eliminar_EmpleadosRequestBody();
            inValue.Body.id = id;
            return ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).Eliminar_EmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientePuntodeVentas.PuntoVentasSW.insert_ProductoResponse ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.insert_Producto(ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequest request) {
            return base.Channel.insert_Producto(request);
        }
        
        public string insert_Producto(ClientePuntodeVentas.PuntoVentasSW.Productos_VO producto) {
            ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequestBody();
            inValue.Body.producto = producto;
            ClientePuntodeVentas.PuntoVentasSW.insert_ProductoResponse retVal = ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).insert_Producto(inValue);
            return retVal.Body.insert_ProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.insert_ProductoResponse> ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap.insert_ProductoAsync(ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequest request) {
            return base.Channel.insert_ProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientePuntodeVentas.PuntoVentasSW.insert_ProductoResponse> insert_ProductoAsync(ClientePuntodeVentas.PuntoVentasSW.Productos_VO producto) {
            ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequest inValue = new ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequest();
            inValue.Body = new ClientePuntodeVentas.PuntoVentasSW.insert_ProductoRequestBody();
            inValue.Body.producto = producto;
            return ((ClientePuntodeVentas.PuntoVentasSW.WebServicePuntodeVentasSoap)(this)).insert_ProductoAsync(inValue);
        }
    }
}
